<?xml version="1.0" encoding="utf-8"?><Database Name="Vehicle" Class="VehicleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=127.0.0.1;Initial Catalog=Vehicle;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="VehicleConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Xe" Member="Xes">
    <Type Name="Xe">
      <Column Name="MaXe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenXe" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="DongXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NamSX" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="KhuyenMai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NgayBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="HinhAnh" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Xe_CTDDH" Member="CTDDHs" ThisKey="MaXe" OtherKey="Xe" Type="CTDDH" />
      <Association Name="Xe_ThongSo" Member="ThongSos" ThisKey="MaXe" OtherKey="MaXe" Type="ThongSo" />
      <Association Name="DongXe_Xe" Member="DongXe1" ThisKey="DongXe" OtherKey="MaDongXe" Type="DongXe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTDDH" Member="CTDDHs">
    <Type Name="CTDDH">
      <Column Name="SoDDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Xe" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="KhuyenMai" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Xe_CTDDH" Member="Xe1" ThisKey="Xe" OtherKey="MaXe" Type="Xe" IsForeignKey="true" />
      <Association Name="DonDatHang_CTDDH" Member="DonDatHang" ThisKey="SoDDH" OtherKey="SoDDH" Type="DonDatHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonDatHang" Member="DonDatHangs">
    <Type Name="DonDatHang">
      <Column Name="SoDDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DaGiaoHang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KhachHang" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="DonDatHang_CTDDH" Member="CTDDHs" ThisKey="SoDDH" OtherKey="SoDDH" Type="CTDDH" />
      <Association Name="User_DonDatHang" Member="User" ThisKey="KhachHang" OtherKey="User1" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DongXe" Member="DongXes">
    <Type Name="DongXe">
      <Column Name="MaDongXe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHangXe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Loai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DongXe_Xe" Member="Xes" ThisKey="MaDongXe" OtherKey="DongXe" Type="Xe" />
      <Association Name="HangXe_DongXe" Member="HangXe" ThisKey="MaHangXe" OtherKey="MaHX" Type="HangXe" IsForeignKey="true" />
      <Association Name="LoaiXe_DongXe" Member="LoaiXe" ThisKey="Loai" OtherKey="MaLoai" Type="LoaiXe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangXe" Member="HangXes">
    <Type Name="HangXe">
      <Column Name="MaHX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenHX" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="QuocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Logo" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="HangXe_DongXe" Member="DongXes" ThisKey="MaHX" OtherKey="MaHangXe" Type="DongXe" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiXe" Member="LoaiXes">
    <Type Name="LoaiXe">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiXe_DongXe" Member="DongXes" ThisKey="MaLoai" OtherKey="Loai" Type="DongXe" />
    </Type>
  </Table>
  <Table Name="dbo.ThongSo" Member="ThongSos">
    <Type Name="ThongSo">
      <Column Name="MaThongSo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaXe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenThongSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThongSo" Member="ThongSo1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Xe_ThongSo" Member="Xe" ThisKey="MaXe" OtherKey="MaXe" Type="Xe" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="[User]" Member="User1" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayDK" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChiThuongTru" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AnhDaiDien" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="User_DonDatHang" Member="DonDatHangs" ThisKey="User1" OtherKey="KhachHang" Type="DonDatHang" />
    </Type>
  </Table>
</Database>